version: "3.8"
services:
  api_v1:
    build:
      dockerfile: Dockerfile_v1_app
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_PORT=5000
    networks:
      - myflaskapi
    entrypoint:
      - python
      - /var/flask/app_v1.py
  api_v2:
    build:
      dockerfile: Dockerfile_v2_app
      context: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_PORT=5001
    networks:
      - myflaskapi
    entrypoint:
      - python
      - /var/flask/app_v2.py
networks:
  myflaskapi:
    name: myflaskapi